using System.Security.Cryptography;
using System.Text;
using Microsoft.AspNetCore.Identity;

namespace StudentManagementSystem.Utilities;

/// <summary>
/// Provides cryptographic functions.
/// </summary>
public class Cryptography
{
    private Cryptography() { }

    /// <summary>
    /// Hashes a string using Microsoft's Identity PasswordHasher.
    /// </summary>
    /// 
    /// <param name="original">The original string.</param>
    /// <param name="salt">The salt to use in the hash.</param>
    /// 
    /// <returns>The new hashed string.</returns>
    public static string Hash(string original, string salt)
    {
        PasswordHasher<string> hasher = new();
        return hasher.HashPassword(salt, original);
    }

    /// <summary>
    /// Verifies a password against a hashed password.
    /// </summary>
    /// 
    /// <param name="userId">The user's salt to verify the hash.</param>
    /// <param name="hashedPw">The hashed password.</param>
    /// <param name="pw">The plaintext password to verify.</param>
    /// 
    /// <returns>true if the password is correct, false otherwise.</returns>
    public static bool Verify(string salt, string hashedPw, string pw)
    {
        PasswordHasher<string> hasher = new();
        return hasher.VerifyHashedPassword(salt, hashedPw, pw) == PasswordVerificationResult.Success;
    }

    /// <summary>
    /// Generates a random 128-bit salt for hashing.
    /// The salt is stored in the SQLite database; because SQLite does not have
    /// a built-in binary type, the salt is converted to a hexadecimal string.
    /// </summary>
    /// 
    /// <returns>The salt in hexadecimal format.</returns>
    public static string GenerateSalt()
    {
        byte[] salt = new byte[128 / 8];
        using (var rng = RandomNumberGenerator.Create())
        {
            rng.GetBytes(salt);
        }
        return BytesToHex(salt);
    }

    /// <summary>
    /// Converts a byte array to a hexadecimal string.
    /// Partially generated by ChatGPT.
    /// </summary>
    /// 
    /// <param name="bytes">The byte array</param>
    /// 
    /// <returns>The hex equivalent.</returns>
    private static string BytesToHex(byte[] bytes)
    {
        StringBuilder hex = new(bytes.Length * 2);
        foreach (byte b in bytes)
        {
            hex.AppendFormat("{0:x2}", b);
        }
        return hex.ToString();
    }
}