using System.Security.Cryptography;
using System.Text;

namespace StudentManagementSystem.Utilities;

public class Cryptography
{
    /// <summary>
    /// Hashes a string using the SHA256 algorithm.
    /// Partially generated by ChatGPT.
    /// </summary>
    /// <param name="original">the original string.</param>
    /// <returns>the new hashed string.</returns>
    public static string Hash(string original)
    {
        byte[] bytes = SHA256.HashData(Encoding.UTF8.GetBytes(original));
        StringBuilder builder = new();
        for (int i = 0; i < bytes.Length; i++)
        {
            builder.Append(bytes[i].ToString("x2")); // x2 formats the byte to a hexadecimal string.
        }
        return builder.ToString();
    }
}