using System.Text.RegularExpressions;

namespace StudentManagementSystem.Utilities;

public partial class RegexValues
{
    private RegexValues() { }

    /// <summary>
    /// A regex pattern for date format DD/MM/YYYY
    /// Regex pattern generated by ChatGPT.
    /// </summary>
    [GeneratedRegex(@"^(0[1-9]|[12][0-9]|3[01])/(0[1-9]|1[012])/\d{4}$")]
    public static partial Regex DateFmtRegex();

    ///
    /// <summary>
    /// A regex pattern for UK postcode format.
    /// Regex pattern from official government documentation: https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/488478/Bulk_Data_Transfer_-_additional_validation_valid_from_12_November_2015.pdf
    /// </summary>
    [GeneratedRegex(@"([Gg][Ii][Rr] 0[Aa]{2})|((([A-Za-z][0-9]{1,2})|(([A-Za-z][A-Ha-hJ-Yj-y][0-9]{1,2})|(([A-Za-z][0-9][A-Za-z])|([A-Za-z][A-Ha-hJ-Yj-y][0-9][A-Za-z]?))))\s?[0-9][A-Za-z]{2})")]
    public static partial Regex PostcodeRegex();

    /// <summary>
    /// A simple regex pattern for email format.
    /// From: https://stackoverflow.com/a/742588/16775139
    /// </summary>
    [GeneratedRegex(@"^[^@\s]+@[^@\s]+\.[^@\s]+$")]
    public static partial Regex EmailRegex();

    /// <summary>
    /// A regex pattern for a user's role.
    /// </summary>
    /// <returns></returns>
    [GeneratedRegex(@"user|admin")]
    public static partial Regex RoleRegex();
}